### ISSUE TITLE
Feat: 인증 및 마이페이지 관련 API 테스트 

### ISSUE THREAD

**Issue by leewooseong** [ggumms/ggumtle-ws-fe#10]
## 🚧 Description
로그인, 회원가입, 마이페이지에서 작성한 API들을 실제로 테스트 해보는 작업 

## ✅ Todo
- [ ] 로그인 API 테스트
- [ ] 회원가입 API 테스트
- [ ] 마이페이지 API 테스트
- [ ] API 통한 테스트 후 라우터 프로텍션 기능 추가
