### ISSUE TITLE
Feat: 대표 버킷 UI 개발

### ISSUE THREAD

**Issue by leewooseong** [ggumms/ggumtle-ws-fe#22]
## 🚧 Description
대표 버킷에 해당하는 UI를 설계 및 개발

## ✅ Todo
- [ ] 기존 UserPage 코드에서 내 정보 표시 부분만 가져와서 적용하기 (대표 버킷 설정 UI를 위한 기반 다지기)
- [ ] 대표 버킷 설정에 대한 Figma 디자인 추가
- [ ] Figma를 기반으로 UI 적용하기
